server:
  port: 8080
  servlet.context-path: /api

spring:
  profiles.active: dev
  application.name: ExamenTecso

  datasource.url: jdbc:postgresql://localhost:5432/postgres
  datasource.username: postgres
  datasource.password: postgres
  jpa.hibernate.ddl-auto: create
  jpa.properties.hibernate.default_schema: tecso
  jpa.show-sql: true
